spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root@lfc
    password: 123456
    url: jdbc:mysql://localhost:3306/liver?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    show-sql: true
    generate-ddl: true
